set shell := ["powershell.exe", "-c"]

build:
  cargo build --release

build-32:
  just setup
  cargo build --target=i686-pc-windows-msvc --release

build-64:
  cargo build --target=x86_64-pc-windows-msvc --release

setup:
  rustup target add i686-pc-windows-msvc